### PR TITLE
change juttle browser icon label from 'path' to 'browse'

### PR DESCRIPTION
**Pull request by go-oleg**
I think "browse" is a better term than "path" because its a verb/call-to-action.

@mnibecker @demmer @dmehra thoughts?

image

### CODE REVIEW

**Comment by demmer** [comment]
How about the classic "open"?

-m

**Comment by go-oleg** [comment]
Thats good too.

**Comment by dmehra** [comment]
i'm good with "open"

**Comment by go-oleg** [comment]
open it is.

**Pull request merged**
