### PR TITLE
Get travis going

### PR DESCRIPTION
**Pull request by mnibecker**
Enable lint, coverage.

We weren't using any of the tests, no do I anticipate that we will be doing selenium stuff so I nuked the test dir for now. We can always bring back the code if we want it (which I double we will).

In a follow up pr I will add some rudimentary unit tests.

@go-oleg @rlgomes

### CODE REVIEW

**Comment by rlgomes** [comment]
At the minimum we should keep the app test that verifies you can spin up a juttle-viewer and run a simple juttle program ? I mean otherwise this is just a huge way of setting us up for regressions before each and every release with absolutely nothing validating you can run like an `emit -limit 1 | view table` kind of program.

**Comment by mnibecker** [comment]
1. I believe the plan was to do this testing in `juttle-engine` 
2. What do we run the program against, do we include `juttle-engine` as a devDependency? Don't like that idea.

**Comment by go-oleg** [comment]
I think these tests should be in `juttle-engine` as well...though the tests that don't involve adapters should be runnable against both (with `juttle-service` being a devDependency).

**Comment by rlgomes** [comment]
@mnibecker +1 with some unit tests you'll be adding on here to have a minimal bandaid of tests.

**Pull request merged**
